base_url = "https://madliani.vercel.app/"
build_search_index = true
compile_sass = true
default_language = "en"
description = "A programmer's personal website."
theme = "even"
title = "madliani"

[markdown]
highlight_code = true

[extra]
